# Workflow for deploying to production environment
name: Deploy Experiment 1 to Production

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ['main']
    paths:
      - 'experiment-1-git/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: './experiment-1-git/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: ./experiment-1-git

      - name: Set DEPLOY_ENV to production
        run: echo "DEPLOY_ENV=production" >> $GITHUB_ENV

      - name: Build
        run: pnpm run build
        working-directory: ./experiment-1-git

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './experiment-1-git/dist/exp-1'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4